# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d79d77a3b2f6f5d2238a6af9d135c4460c8fea4f450c68d390865feb4f1f2030f748befa7285edfe62914a218ca8117006a83562776e350063c1d090c34aeae3

test:
  secret_key_base: ee1b7ef60bff02842c86fffc340d9149478067ba2214c800ff2f8a8f16b44f06543ad82e43588ae98117aa83d6fa98e1a661177242ecd10ba0f3d399bf19c76c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
